stages:
  - test
  - build
  - deploy

test:
  image: python:latest
  stage: test
  script:
    - pip install -r requirements.txt
    - python manage.py test --noinput
  tags:
    - docker

build:
  image: docker
  services:
    - docker:dind
  stage: build
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker build -t ${CI_REGISTRY}/temmishy/procellariidae .
    - docker push ${CI_REGISTRY}/temmishy/procellariidae:${CI_COMMIT_SHORT_SHA}
  tags:
    - docker

deploy:
  stage: deploy
  script:
    - docker-compose pull
    - docker-compose stop web || true
    - docker-compose up -d --force-recreate
  tags:
    - shell