stages:
  - test

testcases:
  image: python:latest
  stage: test
  script:
    - pip install -r requirements.txt
    - python manage.py test --noinput
  tags:
    - docker

build_docker_image
  stage: build
  script: 
    - docker build -t registry.gitlab.com/temmishy/procellariidae .
    - docker push registry.gitlab.com/temmishy/procellariidae
    tags:
      - shell