stages:
  - test
  - build

django tests:
  image: python:latest
  stage: test
  script:
    - pip install -r requirements.txt
    - python manage.py test --noinput
  tags:
    - docker

build image:
  image: docker:20-dind
  services:
    - name: docker:20-dind
      alias: docker
  stage: build
  script: 
    - docker build -t registry.gitlab.com/temmishy/procellariidae .
    - docker push registry.gitlab.com/temmishy/procellariidae
  tags:
    - docker