stages:
  - test
  - build

django tests:
  image: python:latest
  stage: test
  script:
    - pip install -r requirements.txt
    - python manage.py test --noinput
  tags:
    - docker

build image:
  image: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:dind
      command: [ "--tls=false" ]]
  stage: build
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker build -t ${CI_REGISTRY}/temmishy/procellariidae .
    - docker push ${CI_REGISTRY}/temmishy/procellariidae
  tags:
    - docker
